// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type UserServiceUser struct {
	ID          pgtype.UUID
	Phone       string
	FullName    string
	Password    string
	Email       string
	Role        int32
	Address     pgtype.Text
	DateCreated pgtype.Timestamp
}
