// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Fullname    string             `json:"fullname"`
	Username    string             `json:"username"`
	Password    string             `json:"password"`
	Address     string             `json:"address"`
	Phone       string             `json:"phone"`
	DateCreated pgtype.Timestamptz `json:"date_created"`
}
