// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (UserServiceUser, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetUser(ctx context.Context, id pgtype.UUID) (UserServiceUser, error)
	GetUserByPhone(ctx context.Context, phone string) (UserServiceUser, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]UserServiceUser, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UserServiceUser, error)
}

var _ Querier = (*Queries)(nil)
