// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package postgresql

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO user_service.users (
    full_name, password, address, phone
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, phone, full_name, password, address, date_created
`

type CreateUserParams struct {
	FullName string
	Password string
	Address  pgtype.Text
	Phone    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (UserServiceUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.FullName,
		arg.Password,
		arg.Address,
		arg.Phone,
	)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.Password,
		&i.Address,
		&i.DateCreated,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM user_service.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, phone, full_name, password, address, date_created FROM user_service.users 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (UserServiceUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.Password,
		&i.Address,
		&i.DateCreated,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone, full_name, password, address, date_created FROM user_service.users 
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetUserByPhone(ctx context.Context, phone string) (UserServiceUser, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phone)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.Password,
		&i.Address,
		&i.DateCreated,
	)
	return i, err
}

const listUser = `-- name: ListUser :many
SELECT id, phone, full_name, password, address, date_created FROM user_service.users
ORDER BY date_created DESC
LIMIT $1 OFFSET $2
`

type ListUserParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUser(ctx context.Context, arg ListUserParams) ([]UserServiceUser, error) {
	rows, err := q.db.Query(ctx, listUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserServiceUser
	for rows.Next() {
		var i UserServiceUser
		if err := rows.Scan(
			&i.ID,
			&i.Phone,
			&i.FullName,
			&i.Password,
			&i.Address,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE user_service.users
SET password = $2
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID       pgtype.UUID
	Password string
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.Password)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE user_service.users
SET 
    full_name = $2, 
    address = $3
WHERE id = $1
RETURNING id, phone, full_name, password, address, date_created
`

type UpdateUserParams struct {
	ID       pgtype.UUID
	FullName string
	Address  pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UserServiceUser, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.FullName, arg.Address)
	var i UserServiceUser
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.FullName,
		&i.Password,
		&i.Address,
		&i.DateCreated,
	)
	return i, err
}
