// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/ducthangng/geofleet/user-service/internal/handler"
)

// Injectors from wire.go:

// InitializeUserService is the "Injector Stub".
// 1. It defines the Function Signature (what inputs we have, what output we want).
// 2. It tells Wire which Providers to use via wire.Build.
func InitializeUserService(ctx context.Context) (*handler.UserRestfulHandler, error) {
	pool, err := ProvideDBPool(ctx)
	if err != nil {
		return nil, err
	}
	queries := ProvideRepository(pool)
	userUsecaseInteractor := ProvideUserUsecase(queries)
	userRestfulHandler := handler.NewUserRestfulHandler(userUsecaseInteractor)
	return userRestfulHandler, nil
}
