// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/ducthangng/geofleet/user-service/internal/handler"
)

// Injectors from wire.go:

func Initialize(ctx context.Context) (*handler.UserHandler, error) {
	pool, err := ProvideDBPool(ctx)
	if err != nil {
		return nil, err
	}
	queries := ProvideRepository(pool)
	userUsecaseInteractor := ProvideUserUsecase(queries)
	userHandler := handler.NewUserRestfulHandler(userUsecaseInteractor)
	return userHandler, nil
}
