package presenter

import (
	"log"

	"github.com/ducthangng/geofleet/user-service/service/helper"
)

type User struct {
	// ID is usually generated by the system, so we don't validate it for input
	ID string `json:"id"`

	// Fullname: Required, must be at least 2 characters
	Fullname string `json:"fullname" validate:"required,min=2"`

	// Username: Required, must be at least 4 characters
	Username string `json:"username" validate:"required,min=4"`

	// Password: Required, min 8 chars.
	// (Note: For stricter complexity like special chars, you'd use a custom regex)
	Password string `json:"password" validate:"required,min=8"`

	// Address: Required, non-empty
	Address string `json:"address" validate:"required"`

	// Phone: Required, must match international E.164 format (e.g., +14155552671)
	// If you want to allow local numbers (090...), change this to 'required,numeric,min=10'
	Phone string `json:"phone" validate:"required,numeric,min=10"`

	// DateCreate: Usually output-only, so no input validation required
	DateCreate string `json:"dateCreated"`
}

func (u *User) VerifyFullname() bool {
	// check if Fullname or Username contain special characters.
	nameCheck := helper.ContainsSpecialStrict(u.Fullname)
	if !nameCheck {
		return nameCheck
	}

	return true
}

func (u *User) VerifyUsername() bool {
	// check if Fullname or Username contain special characters.
	nameCheck := helper.ContainsSpecialStrict(u.Username)
	if !nameCheck {
		log.Println("name checked fail")
		return nameCheck
	}

	isSQLInjection := helper.IsPossibleSQLInjection(u.Username)
	if isSQLInjection {
		log.Println("name checked sql fail")
		return false
	}

	return true
}

func (u *User) VerifyPassword() bool {
	return len(u.Password) >= 8
}
